import{a as L,S as v,i as a}from"./assets/vendor-DqB7j7Ix.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="51062655-c6be70d0f875c8df0d60bf3cc",S="https://pixabay.com/api/",x=15;async function E(r,t){return(await L.get(S,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:x,page:t}})).data}const u=document.querySelector(".gallery"),d=document.querySelector(".loader"),g=document.querySelector(".load-more"),P=new v(".gallery a");function q(r){const t=r.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:i,comments:y,downloads:b})=>`<li>
      <a href="${n}">
        <img src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> <span>${o}</span></p>
        <p><b>Views:</b> <span>${i}</span></p>
        <p><b>Comments:</b> <span>${y}</span></p>
        <p><b>Downloads:</b> <span>${b}</span></p>
      </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",t),P.refresh()}function B(){u.innerHTML=""}function H(){d.classList.add("visible")}function C(){d.classList.remove("visible")}function I(){g.classList.add("visible")}function l(){g.classList.remove("visible")}const m=document.querySelector(".form"),$=m.elements["search-text"],M=document.querySelector(".load-more");let p="",c=1,f=0;m.addEventListener("submit",async r=>{r.preventDefault();const t=$.value.trim();if(!t){a.info({message:"Please enter a search term"});return}B(),l(),p=t,c=1,await h()});M.addEventListener("click",async()=>{c+=1,await h(!0)});async function h(r=!1){try{H();const t=await E(p,c);if(f=t.totalHits,t.hits.length===0&&!r){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",iconUrl:"/goit-js-hw-10/img/bi_x-octagon.svg",progressBarColor:"#b51b1b",color:"#ef4040",transitionIn:"fadeInDown",maxWidth:"432px"}),l();return}q(t.hits);const s=Math.ceil(f/15);c<s?I():(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",titleColor:"#fff",titleSize:"16px",titleLineHeight:"1.5",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",iconUrl:"/goit-js-hw-10/img/bi_x-octagon.svg",progressBarColor:"#b51b1b",color:"#ef4040",transitionIn:"fadeInDown",maxWidth:"432px"})),r&&_()}catch{a.error({message:"Something went wrong, try again later"})}finally{C()}}function _(){const{height:r}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
